// Code generated by hertz generator.

package api

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	api "note/hertz_gen/api"
)

// CreateUser .
// @router /v1/user/register [POST]
func CreateUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.CreateUserRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.CreateUserResponse)

	c.JSON(consts.StatusOK, resp)
}

// CheckUser .
// @router /v1/user/login [POST]
func CheckUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.CheckUserRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.CheckUserResponse)

	c.JSON(consts.StatusOK, resp)
}

// CreateNote .
// @router /v1/note [POST]
func CreateNote(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.CreateNoteRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.CreateNoteResponse)

	c.JSON(consts.StatusOK, resp)
}

// QueryNote .
// @router /v1/note/query [GET]
func QueryNote(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.QueryNoteRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.QueryNoteResponse)

	c.JSON(consts.StatusOK, resp)
}

// UpdateNote .
// @router /v1/note/:note_id [PUT]
func UpdateNote(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.UpdateNoteRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.UpdateNoteResponse)

	c.JSON(consts.StatusOK, resp)
}

// DeleteNote .
// @router /v1/note/:note_id [DELETE]
func DeleteNote(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.DeleteNoteRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.DeleteNoteResponse)

	c.JSON(consts.StatusOK, resp)
}
